#!/usr/bin/env bash

email_log_dir=$1
if [ ! -d ${email_log_dir} ]; then
    mkdir -p ${email_log_dir}
fi

current_time=$( date +"%Y-%m-%d_%H-%M-%S" )
# Add random suffix to file name just in case there several emails sent in one second
random_suffix=$(( RANDOM % 100 ))
email_file_path="${email_log_dir}/${current_time}_${random_suffix}.out"

echo $(cat) > ${email_file_path}